name: Test, Build, Deploy

on:
  push:
    branches: ["develop", "main"]
  pull_request:
    branches: ["develop", "main"]


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  Solution_Name: Lexicanum.sln
  Build_Configuration: Release                                          # Replace with your solution name, i.e. MyWpfApp.sln.
  Test_Project_Path: Lexicanum.Test\Lexicanum.Test.csproj        # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

jobs:
  validate-branch-rules: 
    name: validate-branch-rules
    runs-on: ubuntu-latest
    steps:
     - name: Feature/bugfix branch message
       if: |
        startsWith(github.head_ref || github.ref_name, 'feature/') ||
        startsWith(github.head_ref || github.ref_name, 'bugfix/')
       run: |
         echo "::notice::Validate Branch Rules: Sucess - continue to run tests"
  
     - name: Skip message
       if: "!startsWith(github.head_ref, 'feature/') && !startsWith(github.head_ref, 'bugfix/')"
       run: |
         echo "::notice::Validate Branch Rules: Fail - only feature/ or bugfix/ syntax acepted as branch names, run-tests, build-deploy canceled"
       
  run-tests:
    name: run-tests
    runs-on: windows-latest
    needs: validate-branch-rules
    if: |
        startsWith(github.head_ref || github.ref_name, 'feature/') ||
        startsWith(github.head_ref || github.ref_name, 'bugfix/')
   
  
    steps:  
  
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: Setup .NET 
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
            
      - name: Restore dependencies
        run: dotnet restore ${{ env.Solution_Name }}
      
      - name: Build solution 
        run: dotnet build ${{ env.Solution_Name }} --configuration ${{ env.Build_Configuration }} --no-restore
      
      # Execute all unit tests in the solution
      - name: Run tests (if test project exists)
        run: dotnet test ${{ env.Solution_Name }} --configuration ${{ env.Build_Configuration }} --no-build --verbosity normal
        continue-on-error: true  # Don't fail if no tests exist yet
    
  build-deploy:
    name: build-and-deploy
    runs-on: windows-latest
    needs: run-tests
          
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      
      - name: Restore dependencies
        run: dotnet restore ${{ env.Solution_Name }}
      
      - name: Build solution  # --no-restore  “I guarantee restore has already been run with compatible settings.”
        run: dotnet build ${{ env.Solution_Name }} --configuration ${{ env.Build_Configuration }} --no-restore  
      
      - name: Publish application  # --no-build  “I guarantee build has already been run with compatible settings.”
        run: |
          dotnet publish Lexicanum\Lexicanum.csproj `
            --configuration ${{ env.Build_Configuration }} `
            --output ./publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Lexicanum-Build-${{ github.run_number }}
          path: ./publish/**/*

    
    
